spring.application.name=SpringExample

spring.thymeleaf.cache=false

spring.datasourec.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasourec.url=jdbc:mysql://localhost:3306/leesongjae
spring.datasourec.username=root
spring.datasourec.password=root

mtbatis.mapper-location=mappers/*Mapper.xml